name: E2E Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '0 2 * * *'  # Run daily at 2 AM

jobs:
  e2e-tests:
    name: End-to-End Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: saaspe_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install backend dependencies
        working-directory: ./SaasPE-Backend
        run: npm ci

      - name: Install frontend dependencies
        working-directory: ./saaspe-web
        run: npm ci

      - name: Setup database
        working-directory: ./SaasPE-Backend
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/saaspe_test
        run: |
          npx prisma generate
          npx prisma migrate deploy
          npx prisma db seed

      - name: Start backend
        working-directory: ./SaasPE-Backend
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/saaspe_test
          REDIS_URL: redis://localhost:6379
          JWT_SECRET: test-secret-key
          NODE_ENV: test
        run: npm run start:dev &
        
      - name: Wait for backend
        run: npx wait-on http://localhost:3000/api/v1/health -t 30000

      - name: Start frontend
        working-directory: ./saaspe-web
        env:
          NEXT_PUBLIC_API_URL: http://localhost:3000/api/v1
        run: npm run dev &

      - name: Wait for frontend
        run: npx wait-on http://localhost:3002 -t 30000

      - name: Install Playwright
        run: npx playwright install --with-deps chromium

      - name: Run E2E tests
        working-directory: ./saaspe-web
        run: npx playwright test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-results
          path: saaspe-web/test-results/

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: saaspe-web/playwright-report/
